project:
  type: website

website:
  title: "Deep Learning - SINAPE"
  navbar:
    left:
      - href: index.qmd
        text: Home
  sidebar:
    contents:
      - href: aula1.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



